name: Download and Release Lua

on:
  workflow_dispatch:

jobs:
  release-lua:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Git
        run: |
          sleep 10
          curl -L https://www.lua.org/ftp/lua-5.5.0.tar.gz | tar xz
          ls
          cd lua-5.5.0
          ls
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git pull
          git add . 
          git commit -m "lua-5.5.0" 
          git push
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            lua-5.5.0.tar.gz
          name: "Lua 5.5.0 Release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

