name: Download and Release Lua

on:
  workflow_dispatch:

jobs:
  release-lua:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get lua
        run: |
          sleep 20
          curl -L https://www.lua.org/ftp/lua-5.5.0.tar.gz | tar xz
          mv lua-5.5.0/* .
          rm -r lua-5.5.0
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git pull
          git add . 
          git commit -m "lua-5.5.0" 
          git push
      - name: Generate release tag
        id: generate_release_tag
        uses: alexvingg/next-release-tag@v1.0.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ''

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            lua-5.5.0.tar.gz
          name: Release ${{ steps.generate_release_tag.outputs.release_tag }}
          tag: ${{ steps.generate_release_tag.outputs.release_tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

